spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/final_project?autoReconnect=true&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: admin
      password: admin

oauth0:
  issuer: https://blog-samples.auth0.com/
  apiAudience: https://contacts.blog-samples.com/